language: python
python:
  - '3.8'
env:
  - TOXENV=quality
  - TOXENV=python
cache:
  - pip
before_install:
  - pip install --upgrade pip
install:
  - pip install -r requirements/travis.txt
script:
  - tox
after_success:
  - codecov
deploy:
  provider: pypi
  user: edx
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: 3.8
    condition: $TOXENV = quality
  password:
    secure: ATJuiHmd4jXT8Se69MnLJVdfgPmWSt6RpdqsCI7nCZRlI5jjJL6hXg/RWflVO/8dw6LWpjsf8BMXe056kZ9q4PPdBtoSvl7LsJ65mJdaJ6CvU17yYgH+lYcbdsG8NeBiqiYtu0TWR5j8vjbbUrQ4dnjdicOAwnbOz4mx2Lm3+3s+GL/gyDhfaZt2wg/lgtRgwhXV5i44vkLCn04M/LO1hUjZLl664nUu5ZzzV8XPxA8v+Qa/RZkbOsacYE1SvkAvGJsknlivha5DOogJoj3T87+J+6Zs0GM2qh9c121H5jD3OhXiH1XUSUORNQ7LeNIVI/dSwR4C4GXyEhjtUIFtojYWo3s/m8zFrH5RS2PUsUaDMszub/GnmzunTi57BuUZIJeG5/2krj+Zlcf1RRjt1krKPUD7DHT6WEVw5dyxzcw00t+rjmaQlevqSuITCP7573RIoJWjdWyhFOjaX2rKbbSnvWd9GBKnRj7HTj9JCXWmGyorl0YL8tWWAa1sZ6W9NW1yRfWp9rjm7vHYh8DVmCbC6Pu7yiu2uR/NiYbaOJJmUG9hJBV9L4hdrAjTq9vurKPS1VDwb/cu14OdbtmT2V2ws0FJ/7IXZAGWK3/vyFm5Z21yHv+KQu6KiBLUbAsJA24O+3L5ScuYBKxIsDzDCzPwzhtxd8D8KSyOJIH0/78=
