coverage:
  status:
    project:
      default:
        enabled: yes
        threshold: 0.1
        target: auto
    patch:
      default:
        enabled: yes
        target: 80%

comment: false

github_checks:
    annotations: false
